# Generated by Django 5.2 on 2025-05-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='BMW', max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('series', models.CharField(max_length=50, verbose_name='Серія')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік випуску')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('power', models.IntegerField(verbose_name='Потужність (к.с.)')),
                ('max_speed', models.IntegerField(verbose_name='Макс. швидкість (км/год)')),
                ('acceleration', models.FloatField(verbose_name='Прискорення (с)')),
                ('range_km', models.IntegerField(verbose_name='Запас ходу (км)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('preferred_date', models.DateField(verbose_name='Бажана дата')),
                ('preferred_time', models.TimeField(verbose_name='Бажаний час')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_requests', to='carsale_app.car', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Заявка на тест-драйв',
                'verbose_name_plural': 'Заявки на тест-драйв',
            },
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_car_brand', models.CharField(max_length=50, verbose_name='Марка авто клієнта')),
                ('customer_car_model', models.CharField(max_length=50, verbose_name='Модель авто клієнта')),
                ('customer_car_year', models.PositiveIntegerField(verbose_name='Рік випуску авто клієнта')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('preferred_date', models.DateField(verbose_name='Бажана дата')),
                ('preferred_time', models.TimeField(verbose_name='Бажаний час')),
                ('dealership', models.CharField(max_length=50, verbose_name='Автосалон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('desired_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in_requests', to='carsale_app.car', verbose_name='Бажаний автомобіль')),
            ],
            options={
                'verbose_name': 'Заявка на Trade-In',
                'verbose_name_plural': 'Заявки на Trade-In',
            },
        ),
    ]
